# Generated by Django 2.2 on 2020-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(default=0, verbose_name='Semilla "X0"')),
                ('c', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='constante aditiva "c"')),
                ('a', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='constante multiplicativa "a"')),
                ('m', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='modulo "m"')),
                ('k', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='coeficiente "k" que modifica a "a"')),
                ('g', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='coeficiente "g" que modifica a "m"')),
                ('method', models.CharField(choices=[('Mi', 'Congruencial Mixto'), ('Mu', 'Congruencial Multiplicativo')], default='Mi', max_length=2, verbose_name='Metodo')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
            },
        ),
    ]
