# Generated by Django 2.2 on 2020-04-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('number_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=4, verbose_name='valor')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number_generator.Data', verbose_name='Data')),
            ],
        ),
    ]
